// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerResourceAccess;

namespace PlayerResourceAccess.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20201024154811_AddedData")]
    partial class AddedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlayerResourceAccess.Entity.GoalStatsDetail", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ForTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameTime")
                        .HasColumnType("int");

                    b.Property<bool>("GoalMadeNotSaved")
                        .HasColumnType("bit");

                    b.Property<Guid>("InLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId");

                    b.ToTable("GoalStatsDetails");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("540eb7bc-95f6-4978-b2a7-57190c27c62a"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 971, DateTimeKind.Local).AddTicks(3696),
                            ForTeamId = new Guid("29090939-1d95-4ac2-ab29-de91a2db1368"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("c7128ccb-09ce-40c4-8a42-9180bab68360")
                        },
                        new
                        {
                            PlayerId = new Guid("6a2e96a5-9876-4e73-9bb3-7bfc0cf772a3"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(1630),
                            ForTeamId = new Guid("091eab68-b90d-4e2c-ad39-87b06b9e46eb"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("4b1f9e19-a606-43e9-ad44-1efac3e8cd0c")
                        },
                        new
                        {
                            PlayerId = new Guid("bd3d62fb-8e71-41f4-a555-a1ae2c8e89d7"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(1818),
                            ForTeamId = new Guid("d9b1b83d-4e3d-45a1-bc68-c7828b92aad4"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("3720d8c3-11e8-4795-9cc6-e58c26ef32c9")
                        },
                        new
                        {
                            PlayerId = new Guid("9ae9e82d-79aa-4cfb-bf39-f18e09e2d6eb"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(1879),
                            ForTeamId = new Guid("8c7e4657-c9bc-4cab-b825-e749cd42c358"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("1ff0169b-d9b5-46af-b0b5-92fbbc0ac76d")
                        },
                        new
                        {
                            PlayerId = new Guid("eee18c0c-1696-4cf6-bb78-b2680da9499d"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(1984),
                            ForTeamId = new Guid("6512a227-b8b0-4aab-95a4-62f44e264bc8"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("23d68bb6-f81e-4bd5-84ad-cd782b6320cd")
                        },
                        new
                        {
                            PlayerId = new Guid("99793a6c-6e50-4a48-b10a-57125f64060f"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2043),
                            ForTeamId = new Guid("ef6ab149-ca29-4ec1-9f22-8875a4aa6bdf"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("03406e0d-6464-470b-aa51-e7a83bb0f60c")
                        },
                        new
                        {
                            PlayerId = new Guid("fe5effd4-02b6-436e-87f9-f51b4f340c23"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2100),
                            ForTeamId = new Guid("13c721dd-c33f-4519-ba1f-712237a06323"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("9cc07c34-2bac-4e45-9cac-a85a240d393c")
                        },
                        new
                        {
                            PlayerId = new Guid("45dd0326-135f-46c1-bb85-a29801da504e"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2154),
                            ForTeamId = new Guid("1a1dc4db-08cb-4ade-a7f4-f8843013c857"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("dc7361e4-9b7c-4a41-bce4-176be1c49441")
                        },
                        new
                        {
                            PlayerId = new Guid("58ce6649-c1fb-473f-9685-6f85ff87b84b"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2208),
                            ForTeamId = new Guid("2b0100f3-18b7-42c5-87e1-6805923f352d"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("a39bd94c-6566-4ef0-80ba-69412ae8a300")
                        },
                        new
                        {
                            PlayerId = new Guid("0682baec-826b-4197-a64c-42c4a6b53e40"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2262),
                            ForTeamId = new Guid("7f61b85f-6c4f-453c-ba64-9d00df45ba8a"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("1fe0998b-8504-475d-b59e-571d1773352a")
                        },
                        new
                        {
                            PlayerId = new Guid("e8fdafee-a7cd-4f1f-8359-b39507f9af93"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2317),
                            ForTeamId = new Guid("52bff2ff-b926-4f4a-8c0b-3ee37b245e2d"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("49fbcee7-c525-480f-9ca8-3c6557d2a8a4")
                        },
                        new
                        {
                            PlayerId = new Guid("fad463d7-abc3-4e1b-b279-d84f52bf8426"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2369),
                            ForTeamId = new Guid("f5779213-14b6-45df-8033-d99355b8315c"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("a9fb103d-5118-4839-8925-0d279306e231")
                        },
                        new
                        {
                            PlayerId = new Guid("78955ce8-fb5c-4c85-99cc-1845b11a0a12"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2461),
                            ForTeamId = new Guid("72ad2911-1718-4196-8bbe-cc75c59318c0"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("7ecbebda-8312-463a-bd5f-4c9441ed3df8")
                        },
                        new
                        {
                            PlayerId = new Guid("3bddf1ee-6be8-4634-aabd-e7a1151c1b50"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2514),
                            ForTeamId = new Guid("9de989da-e454-46af-9faa-2f281cafa48b"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("7030ea78-a034-4ea4-b027-0a71c641eda8")
                        },
                        new
                        {
                            PlayerId = new Guid("8c869811-81fa-47fa-8536-164a9dcd3b69"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2569),
                            ForTeamId = new Guid("793f4d54-481e-42ae-80aa-1e714fd72a45"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("8433662e-bbae-46ba-b3a1-eefcee373c51")
                        },
                        new
                        {
                            PlayerId = new Guid("fcfaeb2c-2ea4-4572-a54e-06673bd2b75b"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2621),
                            ForTeamId = new Guid("e748c6a4-74a1-442a-8d04-3d5309f04129"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("1c5bdb49-518a-420b-992f-89b328bcc28b")
                        },
                        new
                        {
                            PlayerId = new Guid("c50db5c5-7689-41c7-9887-c5ed7b2580a5"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2675),
                            ForTeamId = new Guid("159136ef-515e-472c-bbb7-ca74d5129ae7"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("12c7102a-24a5-49de-8a30-20d3baaca880")
                        },
                        new
                        {
                            PlayerId = new Guid("ae0c3e2b-6268-47bc-9698-1c93d3546829"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2729),
                            ForTeamId = new Guid("a4772a68-55f2-4d03-bf18-1bfe313d2935"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("90778e95-e2bf-4975-9ad1-664f97cd984f")
                        },
                        new
                        {
                            PlayerId = new Guid("6e31581c-777d-4c1a-a5df-efa51b782e6e"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2783),
                            ForTeamId = new Guid("04e9d666-dfcb-4692-8d87-f4840b8549d5"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("c4bd2cf3-2a13-47ea-af72-31922c0eec57")
                        },
                        new
                        {
                            PlayerId = new Guid("742f4d2b-9cfb-4076-a31a-69e214ee3e9b"),
                            At = new DateTime(2020, 10, 24, 17, 48, 10, 975, DateTimeKind.Local).AddTicks(2835),
                            ForTeamId = new Guid("0d5e25bf-f764-4644-bbf3-cf7ab2cff0ad"),
                            GameTime = 73,
                            GoalMadeNotSaved = true,
                            InLeagueId = new Guid("c449b789-41ef-400c-b08a-4dd863be2182")
                        });
                });

            modelBuilder.Entity("PlayerResourceAccess.Entity.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Deffensive")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameIQ")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Offensive")
                        .HasColumnType("int");

                    b.Property<int>("Reaction")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("540eb7bc-95f6-4978-b2a7-57190c27c62a"),
                            Age = 28,
                            Deffensive = 90,
                            Firstname = "Arne",
                            GameIQ = 91,
                            Height = 192,
                            Offensive = 83,
                            Reaction = 90,
                            Stamina = 90,
                            Surname = "Swinton",
                            TeamId = new Guid("29090939-1d95-4ac2-ab29-de91a2db1368"),
                            Weight = 109
                        },
                        new
                        {
                            Id = new Guid("6a2e96a5-9876-4e73-9bb3-7bfc0cf772a3"),
                            Age = 18,
                            Deffensive = 73,
                            Firstname = "Arne",
                            GameIQ = 90,
                            Height = 199,
                            Offensive = 62,
                            Reaction = 95,
                            Stamina = 92,
                            Surname = "Swinton",
                            TeamId = new Guid("091eab68-b90d-4e2c-ad39-87b06b9e46eb"),
                            Weight = 91
                        },
                        new
                        {
                            Id = new Guid("bd3d62fb-8e71-41f4-a555-a1ae2c8e89d7"),
                            Age = 37,
                            Deffensive = 77,
                            Firstname = "Arne",
                            GameIQ = 96,
                            Height = 180,
                            Offensive = 55,
                            Reaction = 94,
                            Stamina = 94,
                            Surname = "Swinton",
                            TeamId = new Guid("d9b1b83d-4e3d-45a1-bc68-c7828b92aad4"),
                            Weight = 79
                        },
                        new
                        {
                            Id = new Guid("9ae9e82d-79aa-4cfb-bf39-f18e09e2d6eb"),
                            Age = 19,
                            Deffensive = 66,
                            Firstname = "Arne",
                            GameIQ = 90,
                            Height = 176,
                            Offensive = 75,
                            Reaction = 96,
                            Stamina = 92,
                            Surname = "Swinton",
                            TeamId = new Guid("8c7e4657-c9bc-4cab-b825-e749cd42c358"),
                            Weight = 94
                        },
                        new
                        {
                            Id = new Guid("eee18c0c-1696-4cf6-bb78-b2680da9499d"),
                            Age = 34,
                            Deffensive = 97,
                            Firstname = "Arne",
                            GameIQ = 94,
                            Height = 185,
                            Offensive = 63,
                            Reaction = 91,
                            Stamina = 90,
                            Surname = "Swinton",
                            TeamId = new Guid("6512a227-b8b0-4aab-95a4-62f44e264bc8"),
                            Weight = 74
                        },
                        new
                        {
                            Id = new Guid("99793a6c-6e50-4a48-b10a-57125f64060f"),
                            Age = 41,
                            Deffensive = 73,
                            Firstname = "Arne",
                            GameIQ = 98,
                            Height = 189,
                            Offensive = 65,
                            Reaction = 98,
                            Stamina = 90,
                            Surname = "Swinton",
                            TeamId = new Guid("ef6ab149-ca29-4ec1-9f22-8875a4aa6bdf"),
                            Weight = 79
                        },
                        new
                        {
                            Id = new Guid("fe5effd4-02b6-436e-87f9-f51b4f340c23"),
                            Age = 33,
                            Deffensive = 58,
                            Firstname = "Arne",
                            GameIQ = 95,
                            Height = 173,
                            Offensive = 58,
                            Reaction = 90,
                            Stamina = 94,
                            Surname = "Swinton",
                            TeamId = new Guid("13c721dd-c33f-4519-ba1f-712237a06323"),
                            Weight = 99
                        },
                        new
                        {
                            Id = new Guid("45dd0326-135f-46c1-bb85-a29801da504e"),
                            Age = 32,
                            Deffensive = 54,
                            Firstname = "Arne",
                            GameIQ = 93,
                            Height = 198,
                            Offensive = 47,
                            Reaction = 90,
                            Stamina = 97,
                            Surname = "Swinton",
                            TeamId = new Guid("1a1dc4db-08cb-4ade-a7f4-f8843013c857"),
                            Weight = 105
                        },
                        new
                        {
                            Id = new Guid("58ce6649-c1fb-473f-9685-6f85ff87b84b"),
                            Age = 25,
                            Deffensive = 78,
                            Firstname = "Arne",
                            GameIQ = 98,
                            Height = 178,
                            Offensive = 93,
                            Reaction = 93,
                            Stamina = 95,
                            Surname = "Swinton",
                            TeamId = new Guid("2b0100f3-18b7-42c5-87e1-6805923f352d"),
                            Weight = 93
                        },
                        new
                        {
                            Id = new Guid("0682baec-826b-4197-a64c-42c4a6b53e40"),
                            Age = 27,
                            Deffensive = 87,
                            Firstname = "Arne",
                            GameIQ = 93,
                            Height = 171,
                            Offensive = 83,
                            Reaction = 91,
                            Stamina = 93,
                            Surname = "Swinton",
                            TeamId = new Guid("7f61b85f-6c4f-453c-ba64-9d00df45ba8a"),
                            Weight = 101
                        },
                        new
                        {
                            Id = new Guid("e8fdafee-a7cd-4f1f-8359-b39507f9af93"),
                            Age = 41,
                            Deffensive = 73,
                            Firstname = "Arne",
                            GameIQ = 92,
                            Height = 172,
                            Offensive = 85,
                            Reaction = 99,
                            Stamina = 94,
                            Surname = "Swinton",
                            TeamId = new Guid("52bff2ff-b926-4f4a-8c0b-3ee37b245e2d"),
                            Weight = 80
                        },
                        new
                        {
                            Id = new Guid("fad463d7-abc3-4e1b-b279-d84f52bf8426"),
                            Age = 18,
                            Deffensive = 51,
                            Firstname = "Arne",
                            GameIQ = 96,
                            Height = 175,
                            Offensive = 68,
                            Reaction = 90,
                            Stamina = 96,
                            Surname = "Swinton",
                            TeamId = new Guid("f5779213-14b6-45df-8033-d99355b8315c"),
                            Weight = 76
                        },
                        new
                        {
                            Id = new Guid("78955ce8-fb5c-4c85-99cc-1845b11a0a12"),
                            Age = 20,
                            Deffensive = 73,
                            Firstname = "Arne",
                            GameIQ = 94,
                            Height = 189,
                            Offensive = 48,
                            Reaction = 99,
                            Stamina = 98,
                            Surname = "Swinton",
                            TeamId = new Guid("72ad2911-1718-4196-8bbe-cc75c59318c0"),
                            Weight = 105
                        },
                        new
                        {
                            Id = new Guid("3bddf1ee-6be8-4634-aabd-e7a1151c1b50"),
                            Age = 32,
                            Deffensive = 52,
                            Firstname = "Arne",
                            GameIQ = 92,
                            Height = 180,
                            Offensive = 96,
                            Reaction = 97,
                            Stamina = 97,
                            Surname = "Swinton",
                            TeamId = new Guid("9de989da-e454-46af-9faa-2f281cafa48b"),
                            Weight = 76
                        },
                        new
                        {
                            Id = new Guid("8c869811-81fa-47fa-8536-164a9dcd3b69"),
                            Age = 32,
                            Deffensive = 47,
                            Firstname = "Arne",
                            GameIQ = 94,
                            Height = 179,
                            Offensive = 87,
                            Reaction = 90,
                            Stamina = 98,
                            Surname = "Swinton",
                            TeamId = new Guid("793f4d54-481e-42ae-80aa-1e714fd72a45"),
                            Weight = 93
                        },
                        new
                        {
                            Id = new Guid("fcfaeb2c-2ea4-4572-a54e-06673bd2b75b"),
                            Age = 25,
                            Deffensive = 71,
                            Firstname = "Arne",
                            GameIQ = 95,
                            Height = 186,
                            Offensive = 50,
                            Reaction = 98,
                            Stamina = 97,
                            Surname = "Swinton",
                            TeamId = new Guid("e748c6a4-74a1-442a-8d04-3d5309f04129"),
                            Weight = 96
                        },
                        new
                        {
                            Id = new Guid("c50db5c5-7689-41c7-9887-c5ed7b2580a5"),
                            Age = 28,
                            Deffensive = 69,
                            Firstname = "Arne",
                            GameIQ = 94,
                            Height = 175,
                            Offensive = 96,
                            Reaction = 99,
                            Stamina = 92,
                            Surname = "Swinton",
                            TeamId = new Guid("159136ef-515e-472c-bbb7-ca74d5129ae7"),
                            Weight = 107
                        },
                        new
                        {
                            Id = new Guid("ae0c3e2b-6268-47bc-9698-1c93d3546829"),
                            Age = 40,
                            Deffensive = 41,
                            Firstname = "Arne",
                            GameIQ = 93,
                            Height = 177,
                            Offensive = 40,
                            Reaction = 91,
                            Stamina = 90,
                            Surname = "Swinton",
                            TeamId = new Guid("a4772a68-55f2-4d03-bf18-1bfe313d2935"),
                            Weight = 90
                        },
                        new
                        {
                            Id = new Guid("6e31581c-777d-4c1a-a5df-efa51b782e6e"),
                            Age = 36,
                            Deffensive = 68,
                            Firstname = "Arne",
                            GameIQ = 90,
                            Height = 170,
                            Offensive = 78,
                            Reaction = 98,
                            Stamina = 91,
                            Surname = "Swinton",
                            TeamId = new Guid("04e9d666-dfcb-4692-8d87-f4840b8549d5"),
                            Weight = 76
                        },
                        new
                        {
                            Id = new Guid("742f4d2b-9cfb-4076-a31a-69e214ee3e9b"),
                            Age = 39,
                            Deffensive = 60,
                            Firstname = "Arne",
                            GameIQ = 98,
                            Height = 182,
                            Offensive = 63,
                            Reaction = 99,
                            Stamina = 90,
                            Surname = "Swinton",
                            TeamId = new Guid("0d5e25bf-f764-4644-bbf3-cf7ab2cff0ad"),
                            Weight = 99
                        });
                });

            modelBuilder.Entity("PlayerResourceAccess.Entity.PlayerAggregatedStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("GoalsMade")
                        .HasColumnType("int");

                    b.Property<int>("GoalsSaved")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Team")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PlayerAggregatedStats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea0fdcb0-8d0f-47a4-b770-f98e7738e7d9"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("540eb7bc-95f6-4978-b2a7-57190c27c62a"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7872f236-2b74-41c9-8702-f53417144bce"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("6a2e96a5-9876-4e73-9bb3-7bfc0cf772a3"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("336c91c1-1cf4-44b7-8adc-229eb19f45b3"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("bd3d62fb-8e71-41f4-a555-a1ae2c8e89d7"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5678a97c-cd99-441f-be38-5a55a3acc810"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("9ae9e82d-79aa-4cfb-bf39-f18e09e2d6eb"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("dbd69dfd-0ae6-47ee-987b-d1963024ff96"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("eee18c0c-1696-4cf6-bb78-b2680da9499d"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("77617889-fb46-4295-a659-f0418df74e63"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("99793a6c-6e50-4a48-b10a-57125f64060f"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("51b34ed2-64f3-4f91-8fc6-b5b8bbb31f01"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("fe5effd4-02b6-436e-87f9-f51b4f340c23"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("027ee014-f0a2-40c3-994e-c70ca61a2d2e"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("45dd0326-135f-46c1-bb85-a29801da504e"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1c340774-dbce-4f06-b441-d6287c7b4aa2"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("58ce6649-c1fb-473f-9685-6f85ff87b84b"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4430729a-49e2-4933-b026-1acb7f0a92ff"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("0682baec-826b-4197-a64c-42c4a6b53e40"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d1e3be08-f470-4ebf-b029-25225e25c150"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("e8fdafee-a7cd-4f1f-8359-b39507f9af93"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("bb80d622-da97-430a-8a4d-6a61bf3dc1ce"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("fad463d7-abc3-4e1b-b279-d84f52bf8426"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("55c42fd4-f1bc-4951-aaad-438b4d598502"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("78955ce8-fb5c-4c85-99cc-1845b11a0a12"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7b8988cf-ff94-4715-9057-6f3afcb562df"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("3bddf1ee-6be8-4634-aabd-e7a1151c1b50"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e112d89a-47a8-4102-87ca-fde3726133e8"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("8c869811-81fa-47fa-8536-164a9dcd3b69"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ad24f748-d872-47e9-8550-8d522990429b"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("fcfaeb2c-2ea4-4572-a54e-06673bd2b75b"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("bbed6536-36d6-4c71-8ac3-642a021b7cc7"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("c50db5c5-7689-41c7-9887-c5ed7b2580a5"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("dfe7f98c-68c1-4c7b-93b9-1d833ad45538"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("ae0c3e2b-6268-47bc-9698-1c93d3546829"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ff572d68-5174-4bf3-b037-d5797cd99e87"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("6e31581c-777d-4c1a-a5df-efa51b782e6e"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0846bdab-281d-4621-8e9b-8182700f2c4c"),
                            Assists = 12,
                            GamesPlayed = 12,
                            GoalsMade = 12,
                            GoalsSaved = 21,
                            LeagueId = new Guid("00000000-0000-0000-0000-000000000000"),
                            MinutesPlayed = 123,
                            PlayerId = new Guid("742f4d2b-9cfb-4076-a31a-69e214ee3e9b"),
                            Team = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
