// <auto-generated />
using System;
using LeagueResourceAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueResourceAccess.Migrations
{
    [DbContext(typeof(ResourceContext))]
    partial class ResourceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueResourceAccess.Entity.GameDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AwayLeagueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeLeagueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("GameDays");
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueTemplateId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            LeagueTemplateId = new Guid("92a5b129-e3c2-4fc1-a437-4b346d2d867d"),
                            Name = "Premieer League"
                        },
                        new
                        {
                            Id = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            LeagueTemplateId = new Guid("92a5b129-e3c2-4fc1-a437-4b346d2d867d"),
                            Name = "EFL Championship"
                        },
                        new
                        {
                            Id = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            LeagueTemplateId = new Guid("2fa6c329-d683-471c-be8f-8aea59aaff13"),
                            Name = "FA Cup"
                        });
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.LeagueTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("LeagueTeams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b40bd7b0-73c2-4fd5-8b0d-dcc9f97074cb"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 1,
                            TeamId = new Guid("29090939-1d95-4ac2-ab29-de91a2db1368")
                        },
                        new
                        {
                            Id = new Guid("e78f14fd-d20e-4001-93b3-d4b9e18e4f19"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 2,
                            TeamId = new Guid("091eab68-b90d-4e2c-ad39-87b06b9e46eb")
                        },
                        new
                        {
                            Id = new Guid("6a052a7a-63c4-4044-a668-131017d4dde1"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 3,
                            TeamId = new Guid("d9b1b83d-4e3d-45a1-bc68-c7828b92aad4")
                        },
                        new
                        {
                            Id = new Guid("48d59e4a-f269-42ca-8fbe-9e501f8ae333"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 4,
                            TeamId = new Guid("8c7e4657-c9bc-4cab-b825-e749cd42c358")
                        },
                        new
                        {
                            Id = new Guid("2173146e-1679-4f43-87da-0dc1eb3ccad9"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 5,
                            TeamId = new Guid("6512a227-b8b0-4aab-95a4-62f44e264bc8")
                        },
                        new
                        {
                            Id = new Guid("eadc0316-d4ba-464e-b8a2-0c78569a9457"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 6,
                            TeamId = new Guid("ef6ab149-ca29-4ec1-9f22-8875a4aa6bdf")
                        },
                        new
                        {
                            Id = new Guid("42ce521c-f4ca-4ac7-ba2c-dd29b54a2bcf"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 7,
                            TeamId = new Guid("13c721dd-c33f-4519-ba1f-712237a06323")
                        },
                        new
                        {
                            Id = new Guid("6a37f097-53b6-4157-a1f4-136326ba857c"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 8,
                            TeamId = new Guid("1a1dc4db-08cb-4ade-a7f4-f8843013c857")
                        },
                        new
                        {
                            Id = new Guid("b47770e0-dd5e-428b-bd86-1a9163b4f351"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 9,
                            TeamId = new Guid("2b0100f3-18b7-42c5-87e1-6805923f352d")
                        },
                        new
                        {
                            Id = new Guid("fc84db75-3d5a-4a5f-82c0-76f86244d820"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 10,
                            TeamId = new Guid("7f61b85f-6c4f-453c-ba64-9d00df45ba8a")
                        },
                        new
                        {
                            Id = new Guid("dd7e029b-1b4a-43e7-bc7f-8760b82beb59"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 11,
                            TeamId = new Guid("52bff2ff-b926-4f4a-8c0b-3ee37b245e2d")
                        },
                        new
                        {
                            Id = new Guid("67e50ed1-aab8-42b9-91dc-d443e1d7d14c"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 12,
                            TeamId = new Guid("f5779213-14b6-45df-8033-d99355b8315c")
                        },
                        new
                        {
                            Id = new Guid("bd2987ce-4dd9-4a5e-82d2-0bfdcd754949"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 13,
                            TeamId = new Guid("72ad2911-1718-4196-8bbe-cc75c59318c0")
                        },
                        new
                        {
                            Id = new Guid("0c3240d3-c03f-4562-8eef-1983614cc6a8"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 14,
                            TeamId = new Guid("9de989da-e454-46af-9faa-2f281cafa48b")
                        },
                        new
                        {
                            Id = new Guid("26d08c04-4fa8-411c-a29d-fb66556f6727"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 15,
                            TeamId = new Guid("793f4d54-481e-42ae-80aa-1e714fd72a45")
                        },
                        new
                        {
                            Id = new Guid("5b957f9b-45fa-4550-8d13-c6a2c254c8f1"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 16,
                            TeamId = new Guid("e748c6a4-74a1-442a-8d04-3d5309f04129")
                        },
                        new
                        {
                            Id = new Guid("83d238de-c811-4886-bcbc-9153ef84a7bb"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 17,
                            TeamId = new Guid("159136ef-515e-472c-bbb7-ca74d5129ae7")
                        },
                        new
                        {
                            Id = new Guid("33c639c1-aca7-4920-ae45-6bc809567d9c"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 18,
                            TeamId = new Guid("a4772a68-55f2-4d03-bf18-1bfe313d2935")
                        },
                        new
                        {
                            Id = new Guid("bc120ca5-53a2-4fed-80e9-99f4149afdee"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 19,
                            TeamId = new Guid("04e9d666-dfcb-4692-8d87-f4840b8549d5")
                        },
                        new
                        {
                            Id = new Guid("7a1ca0c6-5280-46d0-aad0-6bc9b85b4168"),
                            LeagueId = new Guid("2a07367c-6a5c-442d-94d8-5429035e3972"),
                            Rank = 20,
                            TeamId = new Guid("0d5e25bf-f764-4644-bbf3-cf7ab2cff0ad")
                        },
                        new
                        {
                            Id = new Guid("3d00ba04-c982-49a3-b4db-9bfd0bc03e27"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 0,
                            TeamId = new Guid("a3f8eef4-8a92-407a-9402-d7dae78a7499")
                        },
                        new
                        {
                            Id = new Guid("7807627f-e9b2-4051-b9a8-d8f195b342a6"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 1,
                            TeamId = new Guid("bf852fa5-60f6-4104-94dd-71746b309d1b")
                        },
                        new
                        {
                            Id = new Guid("01f86531-b68e-4a09-9dbb-61dadffc5f9e"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 2,
                            TeamId = new Guid("d45e9dfb-7032-40e9-b871-18901f791536")
                        },
                        new
                        {
                            Id = new Guid("031bd56c-6416-47d8-8f11-34a888a91c0d"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 3,
                            TeamId = new Guid("7fd4962c-a1e0-4c18-b7c5-1e2c9748debf")
                        },
                        new
                        {
                            Id = new Guid("46499e77-3efe-47b9-ab3f-dd6274d12a52"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 4,
                            TeamId = new Guid("3fd0e4d7-5574-4de4-957f-41da87b26f5d")
                        },
                        new
                        {
                            Id = new Guid("d708dff6-c783-4e50-a54e-b57c0f96276e"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 5,
                            TeamId = new Guid("ce43f7ea-f0d8-4354-b2ac-c411b216a87b")
                        },
                        new
                        {
                            Id = new Guid("f0587179-c6fc-4365-a871-70780b6639a1"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 6,
                            TeamId = new Guid("7e560e4b-cdc0-4d3d-998b-df9053813467")
                        },
                        new
                        {
                            Id = new Guid("b4b0caa4-9781-47e1-a90a-3403b0389d71"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 7,
                            TeamId = new Guid("76ab740d-8bd5-428a-a2a5-3d63779805f2")
                        },
                        new
                        {
                            Id = new Guid("a0a435f8-692a-4c6e-8093-2e4e5155a69e"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 8,
                            TeamId = new Guid("7be361b9-46bb-4797-98b5-12d985492302")
                        },
                        new
                        {
                            Id = new Guid("e1e5bb20-c8d7-4f01-928d-8feb26054f1c"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 9,
                            TeamId = new Guid("ba6d5954-364c-45cf-a55d-8a207c369761")
                        },
                        new
                        {
                            Id = new Guid("3ec2de15-cc38-4a6b-ae3a-325d55209ff5"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 10,
                            TeamId = new Guid("a596da7e-8406-42ab-ab87-9f103ee47272")
                        },
                        new
                        {
                            Id = new Guid("34cac657-0252-4837-9b0a-83085155efa6"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 11,
                            TeamId = new Guid("3b52b592-a4bc-4b1c-8f7c-4fe467810dac")
                        },
                        new
                        {
                            Id = new Guid("1083d6f1-feeb-4908-9f45-e63ea8a8fe23"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 12,
                            TeamId = new Guid("676aa12b-2d46-4e4d-8dc9-67fecccd2ba5")
                        },
                        new
                        {
                            Id = new Guid("efce1dbe-dab7-4023-9c97-c6ed1e443bb3"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 13,
                            TeamId = new Guid("ae927c9d-fcd1-4bfc-8259-f8014e74b2e5")
                        },
                        new
                        {
                            Id = new Guid("1fc16b77-9f0c-4665-b6e2-5986aed07e2a"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 14,
                            TeamId = new Guid("ef0e5227-f51f-4f7f-9d24-9a6a208c3a15")
                        },
                        new
                        {
                            Id = new Guid("31354e46-8453-40c5-94aa-00594e18dd8f"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 15,
                            TeamId = new Guid("ed671605-1872-4089-8f2e-4cd9a9f68b72")
                        },
                        new
                        {
                            Id = new Guid("41520332-1119-4d48-a135-574ca4a7f522"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 16,
                            TeamId = new Guid("78d33450-f3dc-4bfd-a01f-1a0e91b75f1a")
                        },
                        new
                        {
                            Id = new Guid("a75b5bcd-3e45-4bc5-869f-2ef3230e4b0f"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 17,
                            TeamId = new Guid("38c2bce5-de53-42e4-b61f-b64113c9d463")
                        },
                        new
                        {
                            Id = new Guid("218ea63c-a6cf-47e4-86b7-02febc750bfe"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 18,
                            TeamId = new Guid("446090dc-4edf-49ef-be12-0f337caa5c39")
                        },
                        new
                        {
                            Id = new Guid("5eb417e3-0666-4e8f-b623-90418e70f362"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 19,
                            TeamId = new Guid("ccc7f427-9b43-4149-9d30-d381a86a146d")
                        },
                        new
                        {
                            Id = new Guid("1854dabf-9358-4caf-b4c9-16015fcdb236"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 20,
                            TeamId = new Guid("787aba1d-e768-4c7e-9128-e04fc7f25564")
                        },
                        new
                        {
                            Id = new Guid("daebf396-c4ef-439e-96ff-1270de5c2f03"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 21,
                            TeamId = new Guid("3ba8507e-90de-4c09-97ad-eec460368c6c")
                        },
                        new
                        {
                            Id = new Guid("c73660c9-8b08-458d-b1b1-7218536b4dad"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 22,
                            TeamId = new Guid("0c1c9d69-7d41-4a85-840b-13cff90fc467")
                        },
                        new
                        {
                            Id = new Guid("5fb6a1a9-39bb-4c60-b86a-a9f514f3dc1b"),
                            LeagueId = new Guid("3ab62c3e-89c7-4abf-909c-176f9cd1442d"),
                            Rank = 23,
                            TeamId = new Guid("f9e13d86-cddd-4400-90d5-43571530b7db")
                        },
                        new
                        {
                            Id = new Guid("82d8f0b3-7783-4616-9aae-63df5f2e0b1f"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 1,
                            TeamId = new Guid("29090939-1d95-4ac2-ab29-de91a2db1368")
                        },
                        new
                        {
                            Id = new Guid("d80a0cae-fb4d-4568-b349-7908e7500458"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 50,
                            TeamId = new Guid("a3f8eef4-8a92-407a-9402-d7dae78a7499")
                        },
                        new
                        {
                            Id = new Guid("0f70d537-b59e-4831-928a-5bd4a5493418"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 2,
                            TeamId = new Guid("091eab68-b90d-4e2c-ad39-87b06b9e46eb")
                        },
                        new
                        {
                            Id = new Guid("31787bcc-414b-4b6f-b7ae-4f20ebeca3ba"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 51,
                            TeamId = new Guid("bf852fa5-60f6-4104-94dd-71746b309d1b")
                        },
                        new
                        {
                            Id = new Guid("1e8ff714-e050-47ad-bf37-8c71ad9cc2ee"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 3,
                            TeamId = new Guid("d9b1b83d-4e3d-45a1-bc68-c7828b92aad4")
                        },
                        new
                        {
                            Id = new Guid("92e0d393-fe1f-4c42-a9fa-3bf9f8f88a29"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 52,
                            TeamId = new Guid("d45e9dfb-7032-40e9-b871-18901f791536")
                        },
                        new
                        {
                            Id = new Guid("df9db17e-8fd7-4c85-a6ee-835f2837908e"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 4,
                            TeamId = new Guid("8c7e4657-c9bc-4cab-b825-e749cd42c358")
                        },
                        new
                        {
                            Id = new Guid("2271f4a5-4341-493d-abbb-22c4adb2c429"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 53,
                            TeamId = new Guid("7fd4962c-a1e0-4c18-b7c5-1e2c9748debf")
                        },
                        new
                        {
                            Id = new Guid("56c2faf0-6806-4114-be4a-c3ef181af824"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 5,
                            TeamId = new Guid("6512a227-b8b0-4aab-95a4-62f44e264bc8")
                        },
                        new
                        {
                            Id = new Guid("47b0e245-0634-4413-ad98-391673321c8b"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 54,
                            TeamId = new Guid("3fd0e4d7-5574-4de4-957f-41da87b26f5d")
                        },
                        new
                        {
                            Id = new Guid("58af8d91-ad16-4364-95f2-030e20ded96b"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 6,
                            TeamId = new Guid("ef6ab149-ca29-4ec1-9f22-8875a4aa6bdf")
                        },
                        new
                        {
                            Id = new Guid("5d83c7a6-059f-41a1-b1bc-4335783c8f1c"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 55,
                            TeamId = new Guid("ce43f7ea-f0d8-4354-b2ac-c411b216a87b")
                        },
                        new
                        {
                            Id = new Guid("7cb54c88-4eb3-40bf-911d-9a6975cb9fc5"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 7,
                            TeamId = new Guid("13c721dd-c33f-4519-ba1f-712237a06323")
                        },
                        new
                        {
                            Id = new Guid("f834ab9d-0ab4-4ddb-ba80-962d8fa78120"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 56,
                            TeamId = new Guid("7e560e4b-cdc0-4d3d-998b-df9053813467")
                        },
                        new
                        {
                            Id = new Guid("235daa1f-eec7-4ab8-8da8-d06c19ea13c8"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 8,
                            TeamId = new Guid("1a1dc4db-08cb-4ade-a7f4-f8843013c857")
                        },
                        new
                        {
                            Id = new Guid("703d884f-c38d-4278-bc5d-d6157cf5a7ab"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 57,
                            TeamId = new Guid("76ab740d-8bd5-428a-a2a5-3d63779805f2")
                        },
                        new
                        {
                            Id = new Guid("936bf90e-3faf-46eb-9ef4-85bc4bd20eba"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 9,
                            TeamId = new Guid("2b0100f3-18b7-42c5-87e1-6805923f352d")
                        },
                        new
                        {
                            Id = new Guid("c9147e42-94c1-45de-9f02-65d3433364fb"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 58,
                            TeamId = new Guid("7be361b9-46bb-4797-98b5-12d985492302")
                        },
                        new
                        {
                            Id = new Guid("1f93cf27-90ed-40d3-acca-6839eafe4352"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 10,
                            TeamId = new Guid("7f61b85f-6c4f-453c-ba64-9d00df45ba8a")
                        },
                        new
                        {
                            Id = new Guid("846b4d57-6be1-4631-b33e-9016895c0088"),
                            LeagueId = new Guid("dfe40feb-4d01-4fcd-a58f-57a8d36831c0"),
                            Rank = 59,
                            TeamId = new Guid("ba6d5954-364c-45cf-a55d-8a207c369761")
                        });
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.LeagueTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEliminiatingCup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsOnDraw")
                        .HasColumnType("int");

                    b.Property<int>("PointsOnWin")
                        .HasColumnType("int");

                    b.Property<int>("TimesPlayingEachOther")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeagueTemplate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fa6c329-d683-471c-be8f-8aea59aaff13"),
                            IsEliminiatingCup = true,
                            Name = "Cup template",
                            PointsOnDraw = 0,
                            PointsOnWin = 0,
                            TimesPlayingEachOther = 0
                        },
                        new
                        {
                            Id = new Guid("92a5b129-e3c2-4fc1-a437-4b346d2d867d"),
                            IsEliminiatingCup = false,
                            Name = "Series template",
                            PointsOnDraw = 1,
                            PointsOnWin = 3,
                            TimesPlayingEachOther = 2
                        });
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.Scorer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssistedByLeaguePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoredInMinute")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScorerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameDayId");

                    b.HasIndex("ScorerId");

                    b.ToTable("Scorers");
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwayGames")
                        .HasColumnType("int");

                    b.Property<int>("AwayWins")
                        .HasColumnType("int");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsMade")
                        .HasColumnType("int");

                    b.Property<int>("HomeGames")
                        .HasColumnType("int");

                    b.Property<int>("HomeWins")
                        .HasColumnType("int");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.GameDay", b =>
                {
                    b.HasOne("LeagueResourceAccess.Entity.League", null)
                        .WithMany("GameDays")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.League", b =>
                {
                    b.HasOne("LeagueResourceAccess.Entity.LeagueTemplate", "LeagueTemplate")
                        .WithMany()
                        .HasForeignKey("LeagueTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.LeagueTeam", b =>
                {
                    b.HasOne("LeagueResourceAccess.Entity.League", null)
                        .WithMany("LeagueTeams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.Scorer", b =>
                {
                    b.HasOne("LeagueResourceAccess.Entity.GameDay", null)
                        .WithMany("HomeScorers")
                        .HasForeignKey("GameDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueResourceAccess.Entity.GameDay", null)
                        .WithMany("AwayScorers")
                        .HasForeignKey("ScorerId");
                });

            modelBuilder.Entity("LeagueResourceAccess.Entity.Standing", b =>
                {
                    b.HasOne("LeagueResourceAccess.Entity.League", null)
                        .WithMany("Standings")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
