// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamResourceAccess;

namespace TeamResourceAccess.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20201024145548_UpdatedIdToFixed")]
    partial class UpdatedIdToFixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamResourceAccess.Entity.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "London",
                            Population = 8982000
                        },
                        new
                        {
                            CityId = new Guid("85e36e3e-c82c-42ef-8abe-bd4dab8330a6"),
                            Name = "Birmingham",
                            Population = 1086000
                        },
                        new
                        {
                            CityId = new Guid("0dc27382-45b0-45e5-8bea-5c694909a290"),
                            Name = "Brighton & Hove",
                            Population = 229700
                        },
                        new
                        {
                            CityId = new Guid("d24188c9-644e-4e51-ba8d-d9ffcfd24954"),
                            Name = "Burnley",
                            Population = 87300
                        },
                        new
                        {
                            CityId = new Guid("369d69e3-966c-40f9-85a8-4df20cea29b8"),
                            Name = "Liverpool",
                            Population = 552267
                        },
                        new
                        {
                            CityId = new Guid("146ee191-8c3b-4c21-8889-47ad0222a5fa"),
                            Name = "Manchester",
                            Population = 5107467
                        },
                        new
                        {
                            CityId = new Guid("b880e420-84e7-48cd-96bd-ebfd02d7ce0c"),
                            Name = "Leeds",
                            Population = 474632
                        },
                        new
                        {
                            CityId = new Guid("8a90901a-340a-4e2f-989f-8f874d354edf"),
                            Name = "Leicester",
                            Population = 329839
                        },
                        new
                        {
                            CityId = new Guid("37340c2c-2c9e-448b-9fb7-bb35bd747780"),
                            Name = "Newcastle",
                            Population = 268064
                        },
                        new
                        {
                            CityId = new Guid("66300e5b-5e68-49c6-8286-ba74b045f54a"),
                            Name = "Sheffield",
                            Population = 518090
                        },
                        new
                        {
                            CityId = new Guid("ee4c692d-ae5a-4230-9d66-e3a071cdeca4"),
                            Name = "Southampton",
                            Population = 253651
                        },
                        new
                        {
                            CityId = new Guid("6826604e-3432-4f53-a68f-3a9770292c3f"),
                            Name = "West Bromwich",
                            Population = 77997
                        },
                        new
                        {
                            CityId = new Guid("f5b1edea-f64d-4942-8f5d-32441a77303c"),
                            Name = "Wolverhampton",
                            Population = 77997
                        });
                });

            modelBuilder.Entity("TeamResourceAccess.Entity.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArenaCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ArenaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("CityId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("29090939-1d95-4ac2-ab29-de91a2db1368"),
                            ArenaCapacity = 60704,
                            ArenaName = "Emirates Stadium",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            TeamId = new Guid("091eab68-b90d-4e2c-ad39-87b06b9e46eb"),
                            ArenaCapacity = 42749,
                            ArenaName = "Villa Park",
                            CityId = new Guid("85e36e3e-c82c-42ef-8abe-bd4dab8330a6"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            TeamId = new Guid("d9b1b83d-4e3d-45a1-bc68-c7828b92aad4"),
                            ArenaCapacity = 30750,
                            ArenaName = "American Express Community Stadium",
                            CityId = new Guid("0dc27382-45b0-45e5-8bea-5c694909a290"),
                            Name = "Brighton & Hove Albion"
                        },
                        new
                        {
                            TeamId = new Guid("8c7e4657-c9bc-4cab-b825-e749cd42c358"),
                            ArenaCapacity = 21944,
                            ArenaName = "Turf Moor",
                            CityId = new Guid("d24188c9-644e-4e51-ba8d-d9ffcfd24954"),
                            Name = "Burnley"
                        },
                        new
                        {
                            TeamId = new Guid("6512a227-b8b0-4aab-95a4-62f44e264bc8"),
                            ArenaCapacity = 41631,
                            ArenaName = "Stamford Bridge",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "Chelsea"
                        },
                        new
                        {
                            TeamId = new Guid("ef6ab149-ca29-4ec1-9f22-8875a4aa6bdf"),
                            ArenaCapacity = 26125,
                            ArenaName = "Selhurst Park",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "Crystal Palace"
                        },
                        new
                        {
                            TeamId = new Guid("13c721dd-c33f-4519-ba1f-712237a06323"),
                            ArenaCapacity = 39572,
                            ArenaName = "Goodison Park",
                            CityId = new Guid("369d69e3-966c-40f9-85a8-4df20cea29b8"),
                            Name = "Everton"
                        },
                        new
                        {
                            TeamId = new Guid("1a1dc4db-08cb-4ade-a7f4-f8843013c857"),
                            ArenaCapacity = 25700,
                            ArenaName = "Craven Cottage",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "Fulham"
                        },
                        new
                        {
                            TeamId = new Guid("2b0100f3-18b7-42c5-87e1-6805923f352d"),
                            ArenaCapacity = 37890,
                            ArenaName = "Elland Road",
                            CityId = new Guid("b880e420-84e7-48cd-96bd-ebfd02d7ce0c"),
                            Name = "Leeds United"
                        },
                        new
                        {
                            TeamId = new Guid("7f61b85f-6c4f-453c-ba64-9d00df45ba8a"),
                            ArenaCapacity = 32312,
                            ArenaName = "King Power Stadium",
                            CityId = new Guid("8a90901a-340a-4e2f-989f-8f874d354edf"),
                            Name = "Leicester City"
                        },
                        new
                        {
                            TeamId = new Guid("52bff2ff-b926-4f4a-8c0b-3ee37b245e2d"),
                            ArenaCapacity = 54074,
                            ArenaName = "Anfield",
                            CityId = new Guid("369d69e3-966c-40f9-85a8-4df20cea29b8"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            TeamId = new Guid("f5779213-14b6-45df-8033-d99355b8315c"),
                            ArenaCapacity = 55097,
                            ArenaName = "Etihad Stadium",
                            CityId = new Guid("146ee191-8c3b-4c21-8889-47ad0222a5fa"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            TeamId = new Guid("72ad2911-1718-4196-8bbe-cc75c59318c0"),
                            ArenaCapacity = 74994,
                            ArenaName = "Old Trafford",
                            CityId = new Guid("146ee191-8c3b-4c21-8889-47ad0222a5fa"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            TeamId = new Guid("9de989da-e454-46af-9faa-2f281cafa48b"),
                            ArenaCapacity = 52354,
                            ArenaName = "St James' Park",
                            CityId = new Guid("37340c2c-2c9e-448b-9fb7-bb35bd747780"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            TeamId = new Guid("793f4d54-481e-42ae-80aa-1e714fd72a45"),
                            ArenaCapacity = 32609,
                            ArenaName = "Bramall Lane",
                            CityId = new Guid("66300e5b-5e68-49c6-8286-ba74b045f54a"),
                            Name = "Sheffield United"
                        },
                        new
                        {
                            TeamId = new Guid("e748c6a4-74a1-442a-8d04-3d5309f04129"),
                            ArenaCapacity = 32505,
                            ArenaName = "St Mary's Stadium",
                            CityId = new Guid("ee4c692d-ae5a-4230-9d66-e3a071cdeca4"),
                            Name = "Southampton"
                        },
                        new
                        {
                            TeamId = new Guid("159136ef-515e-472c-bbb7-ca74d5129ae7"),
                            ArenaCapacity = 62062,
                            ArenaName = "Tottenham Hotspur Stadium",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "Tottenham Hotspur"
                        },
                        new
                        {
                            TeamId = new Guid("a4772a68-55f2-4d03-bf18-1bfe313d2935"),
                            ArenaCapacity = 26688,
                            ArenaName = "The Hawthorns",
                            CityId = new Guid("6826604e-3432-4f53-a68f-3a9770292c3f"),
                            Name = "West Bromwich Albion"
                        },
                        new
                        {
                            TeamId = new Guid("04e9d666-dfcb-4692-8d87-f4840b8549d5"),
                            ArenaCapacity = 60000,
                            ArenaName = "Londons Olympiastadion",
                            CityId = new Guid("e6702b3d-efba-4cf5-96f8-2d6a04a0afa6"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            TeamId = new Guid("0d5e25bf-f764-4644-bbf3-cf7ab2cff0ad"),
                            ArenaCapacity = 32050,
                            ArenaName = "Molineux Stadium",
                            CityId = new Guid("f5b1edea-f64d-4942-8f5d-32441a77303c"),
                            Name = "Wolverhampton Wanderers"
                        });
                });

            modelBuilder.Entity("TeamResourceAccess.Entity.Team", b =>
                {
                    b.HasOne("TeamResourceAccess.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
