// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamResourceAccess;

namespace TeamResourceAccess.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20201006125832_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamResourceAccess.Entity.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "London",
                            Population = 8982000
                        },
                        new
                        {
                            CityId = new Guid("05436ac7-5fb0-41f0-9939-f5e95c99db52"),
                            Name = "Birmingham",
                            Population = 1086000
                        },
                        new
                        {
                            CityId = new Guid("b6fe9a4c-1335-4138-a0b6-b346877119de"),
                            Name = "Brighton & Hove",
                            Population = 229700
                        },
                        new
                        {
                            CityId = new Guid("d579678f-471f-4baa-a287-2e79b68c5831"),
                            Name = "Burnley",
                            Population = 87300
                        },
                        new
                        {
                            CityId = new Guid("b91daa8f-0264-49de-902b-d37dcaa6747c"),
                            Name = "Liverpool",
                            Population = 552267
                        },
                        new
                        {
                            CityId = new Guid("43ce358e-69c1-4057-8858-9c5d9e348ca1"),
                            Name = "Manchester",
                            Population = 5107467
                        },
                        new
                        {
                            CityId = new Guid("9393f183-f7b0-429b-be8f-621d064376d7"),
                            Name = "Leeds",
                            Population = 474632
                        },
                        new
                        {
                            CityId = new Guid("5909027d-5015-46a8-b9c8-a97b69c07f51"),
                            Name = "Leicester",
                            Population = 329839
                        },
                        new
                        {
                            CityId = new Guid("873696eb-739d-418f-9b87-f6426877d898"),
                            Name = "Newcastle",
                            Population = 268064
                        },
                        new
                        {
                            CityId = new Guid("977529f5-e55a-4ff4-903f-ea6461b9615e"),
                            Name = "Sheffield",
                            Population = 518090
                        },
                        new
                        {
                            CityId = new Guid("ea7e18da-299d-4a7b-a30e-39aa6b3c1150"),
                            Name = "Southampton",
                            Population = 253651
                        },
                        new
                        {
                            CityId = new Guid("9ebd32aa-d855-4e2c-bb62-0163bf72731a"),
                            Name = "West Bromwich",
                            Population = 77997
                        },
                        new
                        {
                            CityId = new Guid("2516ced0-f6a5-458a-ac44-be956c96efa4"),
                            Name = "Wolverhampton",
                            Population = 77997
                        });
                });

            modelBuilder.Entity("TeamResourceAccess.Entity.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArenaCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ArenaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("CityId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("5af268a1-4fa7-4005-a6a6-7b8043369099"),
                            ArenaCapacity = 60704,
                            ArenaName = "Emirates Stadium",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            TeamId = new Guid("68db61d7-c3ea-4b9b-8f6b-77d406e56d38"),
                            ArenaCapacity = 42749,
                            ArenaName = "Villa Park",
                            CityId = new Guid("05436ac7-5fb0-41f0-9939-f5e95c99db52"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            TeamId = new Guid("e054c5ab-cfaf-4922-bcff-f11d25ca8603"),
                            ArenaCapacity = 30750,
                            ArenaName = "American Express Community Stadium",
                            CityId = new Guid("b6fe9a4c-1335-4138-a0b6-b346877119de"),
                            Name = "Brighton & Hove Albion"
                        },
                        new
                        {
                            TeamId = new Guid("30d920d8-5b28-4bf6-85f0-83749e20839a"),
                            ArenaCapacity = 21944,
                            ArenaName = "Turf Moor",
                            CityId = new Guid("d579678f-471f-4baa-a287-2e79b68c5831"),
                            Name = "Burnley"
                        },
                        new
                        {
                            TeamId = new Guid("ba21570b-8024-470c-93a5-e65e44ac2f39"),
                            ArenaCapacity = 41631,
                            ArenaName = "Stamford Bridge",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "Chelsea"
                        },
                        new
                        {
                            TeamId = new Guid("95338159-781c-466a-a92b-3438d2c30805"),
                            ArenaCapacity = 26125,
                            ArenaName = "Selhurst Park",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "Crystal Palace"
                        },
                        new
                        {
                            TeamId = new Guid("a0211fe7-a5e2-4e3a-b3f7-4022aeedf913"),
                            ArenaCapacity = 39572,
                            ArenaName = "Goodison Park",
                            CityId = new Guid("b91daa8f-0264-49de-902b-d37dcaa6747c"),
                            Name = "Everton"
                        },
                        new
                        {
                            TeamId = new Guid("d1442bcb-adae-4f6d-9f6d-a39bfb98c82f"),
                            ArenaCapacity = 25700,
                            ArenaName = "Craven Cottage",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "Fulham"
                        },
                        new
                        {
                            TeamId = new Guid("380b51f9-e320-417c-b5a2-c5350b4d237e"),
                            ArenaCapacity = 37890,
                            ArenaName = "Elland Road",
                            CityId = new Guid("9393f183-f7b0-429b-be8f-621d064376d7"),
                            Name = "Leeds United"
                        },
                        new
                        {
                            TeamId = new Guid("28e14756-07e0-45e2-b6d1-2e31d45d30de"),
                            ArenaCapacity = 32312,
                            ArenaName = "King Power Stadium",
                            CityId = new Guid("5909027d-5015-46a8-b9c8-a97b69c07f51"),
                            Name = "Leicester City"
                        },
                        new
                        {
                            TeamId = new Guid("de980dbf-f051-4ec1-988d-8c7f3d4e9461"),
                            ArenaCapacity = 54074,
                            ArenaName = "Anfield",
                            CityId = new Guid("b91daa8f-0264-49de-902b-d37dcaa6747c"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            TeamId = new Guid("19e7888b-8991-4eaf-9b50-048882907567"),
                            ArenaCapacity = 55097,
                            ArenaName = "Etihad Stadium",
                            CityId = new Guid("43ce358e-69c1-4057-8858-9c5d9e348ca1"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            TeamId = new Guid("cd1854b0-db0d-44b2-9be2-13e3beeef948"),
                            ArenaCapacity = 74994,
                            ArenaName = "Old Trafford",
                            CityId = new Guid("43ce358e-69c1-4057-8858-9c5d9e348ca1"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            TeamId = new Guid("6a1c09ff-bfba-4de4-80ee-0ba8b22893da"),
                            ArenaCapacity = 52354,
                            ArenaName = "St James' Park",
                            CityId = new Guid("873696eb-739d-418f-9b87-f6426877d898"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            TeamId = new Guid("36b5f68e-3c7d-4e02-b762-87cb0d188059"),
                            ArenaCapacity = 32609,
                            ArenaName = "Bramall Lane",
                            CityId = new Guid("977529f5-e55a-4ff4-903f-ea6461b9615e"),
                            Name = "Sheffield United"
                        },
                        new
                        {
                            TeamId = new Guid("d7657658-e19e-419e-939b-761a56cbe8ff"),
                            ArenaCapacity = 32505,
                            ArenaName = "St Mary's Stadium",
                            CityId = new Guid("ea7e18da-299d-4a7b-a30e-39aa6b3c1150"),
                            Name = "Southampton"
                        },
                        new
                        {
                            TeamId = new Guid("01414cc2-6167-4f9d-9788-de3f605d26cc"),
                            ArenaCapacity = 62062,
                            ArenaName = "Tottenham Hotspur Stadium",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "Tottenham Hotspur"
                        },
                        new
                        {
                            TeamId = new Guid("cefc13ba-fcdf-4ab6-b862-bec6a70fd81f"),
                            ArenaCapacity = 26688,
                            ArenaName = "The Hawthorns",
                            CityId = new Guid("9ebd32aa-d855-4e2c-bb62-0163bf72731a"),
                            Name = "West Bromwich Albion"
                        },
                        new
                        {
                            TeamId = new Guid("d2dadc8f-8d84-429e-8d75-6ae37241efb5"),
                            ArenaCapacity = 60000,
                            ArenaName = "Londons Olympiastadion",
                            CityId = new Guid("898269d8-b79e-465c-9d40-8d8f577f7a2e"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            TeamId = new Guid("5c3da3dc-35e3-4099-bc9a-258491e8ae21"),
                            ArenaCapacity = 32050,
                            ArenaName = "Molineux Stadium",
                            CityId = new Guid("2516ced0-f6a5-458a-ac44-be956c96efa4"),
                            Name = "Wolverhampton Wanderers"
                        });
                });

            modelBuilder.Entity("TeamResourceAccess.Entity.Team", b =>
                {
                    b.HasOne("TeamResourceAccess.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
